version: '3'

services:
  dice-db:
    image: postgres
    volumes:
      - ../gm-dice/tmp/db:/var/lib/postgresql/data
  dice:
    build: ../gm-dice
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ../gm-dice:/app
    ports:
      - "4000:3000"
    depends_on:
      - dice-db
  treasure-db:
    image: postgres
    volumes:
      - ../gm-treasure/tmp/db:/var/lib/postgresql/data
  treasure:
    build: ../gm-treasure
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ../gm-treasure:/app
    ports:
      - "4010:3000"
    depends_on:
      - treasure-db
